FROM python:3.7-alpine

RUN apk update && apk add --no-cache \
  bash \
  alpine-sdk \
  cmake \
  curl-dev \
  bsd-compat-headers \
  perl \
  mosquitto-clients \
  jq \
  && rm -fr /tmp/*

# Copy over kafkatools installation
COPY --from=pdouble16/kafkacat:1.4.0-r1 /usr/local/bin/kafkacat /usr/local/bin/kafkacat

# Install requests (REST API client)
RUN pip install requests

# Copy over the source
COPY achatina.py /
WORKDIR /

# Run the daemon
CMD python achatina.py
