FROM python:3.7-alpine

RUN apk update && apk add --no-cache \
  bash \
  mosquitto-clients \
  jq \
  kafkacat \
  && rm -fr /tmp/*

# Install requests (REST API client)
RUN pip install requests

# Copy over the source
COPY achatina.py /
WORKDIR /

# Run the daemon
CMD python achatina.py
